### ISSUE TITLE
encrypted gists

### ISSUE THREAD

**Issue by Shea690901** [jdowner/gist#47] opened 2018-02-18 18:58 UTC
When working with unecrypted gists everything I've tested so far (create/list/delete) works just fine, sadly the same can't be said about encrypted gists:

```
$ echo test | gist create dummy -encrypt
{timestamp} ERROR[gist] 'html_url'
```

**Comment by jdowner** [comment] 2018-02-18 20:04
The ```encypt``` flag requires two dashes in front.

**Comment by Shea690901** [comment] 2018-02-19 00:05
Oops, typo in the issue (not the command tried!!!)...

**Comment by jdowner** [comment] 2018-02-19 01:52
No problem. What is the command that you tried?

**Comment by Shea690901** [comment] 2018-02-19 22:55
```echo test | gist create dummy --encrypt``` and ```gist create dummy -encrypt```

both with exactly the same result (except for the timestamp of course ;) )

**Comment by jdowner** [comment] 2018-02-19 23:31
Have you configured gist to use gnupg? https://github.com/jdowner/gist#configuration

**Comment by Shea690901** [comment] 2018-02-21 20:35
Yep...

```
[gist]
token: XXXX
editor: /usr/bin/vim
gnupg-homedir: /home/Rene/.gnupg
gnupg-fingerprint: XXXX
```
(The XXXX of course represent the correct values)

**Comment by jdowner** [comment] 2018-02-21 23:47
Would you mind running this short script for me? It just encrypts a short message and then tries to decrypt it. I'm just trying to narrow down where the problem is coming from.

```
#!/usr/bin/env python

import os
import gnupg


def main():

    gpg = gnupg.GPG(gnupghome=os.path.expanduser("~/.gnupg"))

    fingerprint = "<your gpg fringerprint>"
    message = "test message"

    # Encrypt message
    ciphertext = gpg.encrypt(message, fingerprint)
    print(ciphertext.status)

    # Decrypt message
    plaintext = gpg.decrypt(ciphertext.data)
    print(plaintext.status)


if __name__ == "__main__":
    main()
```

**Comment by Shea690901** [comment] 2018-02-22 22:16
Problem, thanks to your script, partly solved:

I'm using ```gpg2```(!!!), when your script gave me an error message I generated a gpg-key and nearly everything worked fine....
Nearly because while the creation of an encrypted gist now worked as expected, ```gist content XXXX --decrypt``` (like the decryption part of your test script) worked only as long as the private key isn't protected by a passphrase!!!
Since that obviously is a no go, I've got two new questions:

1. Is it planed to switch to the newer gpg version?
2. How do I supply the passphrase? (hopefully not via environment or commandline, both are no goes!)

**Comment by jdowner** [comment] 2018-02-23 01:11
It sounds like you need to install some version of pinentry. pinentry allows you to securely enter your passphrase. There are a variety of different pinentry packages,

* pinetry-curses
* pinetry-qt4
* pinentry-gtk2

It sounds like you want something like pinetry-gtk2. That will bring up a window for you to enter your passphrase whenever you want to decrypt a file with gnupg.

The issue of gpg versus gpg2 is a little awkward. The package I use in gist is python-gnupg. It tries to use whatever you have on your system. Apparently there is an issue with gpg2 on windows, and so the recommendation that comes with python-gnupg is to use v1.4.x. As such, I don't want to require that users install gpg2.

**Comment by Shea690901** [comment] 2018-02-23 18:32
Ouch, and currently I've got only a windoze machine (using cygwin)...

Which also means, that I've got pinentry-w32 installed (yes!, it is already installed!!!)

**Comment by jdowner** [comment] 2018-02-24 19:14
So I just wanted to make sure: this issue is resolve for you?

**Comment by Shea690901** [comment] 2018-02-24 21:27
Not truly...
OK, the gpg2 part is unfortunate, but understandable...

But there is still the problem concerning the password...
As I wrote:
I *have* pinentry installed, neverthelessm there was no request for a password....
I know, that the pinentry is working, since it got called when generating the gpg2 key, though not for the gpg key, for that one I just got a standard request in the tty and also nothing when using --decrypt for gist...

**Comment by jdowner** [comment] 2018-02-24 21:38
It sounds like this is an issue with gpg-agent not running or not configured with the correct pinetry. But, that is something outside of gist so I am going to close this issue.

**Closed by jdowner** 2018-02-24 21:38 UTC

**Comment by Shea690901** [comment] 2018-02-24 21:41
Ah!!!
Ok, that last comment most likely solved the problem (while pinentry was a cygwin requirement to install gpg2, it was previously unknown by me...)
