### ISSUE TITLE
Error message when API fails: ERROR[gist] 'html_url'

### ISSUE THREAD

**Issue by wookayin** [jdowner/gist#59] opened 2019-04-08 01:44 UTC
Creating any ~private~ gist doesn't work. Poor error message.

```
❯❯❯ gist create "desc" desc.py
1554687812.729 ERROR[gist] 'html_url'
```

**Comment by wookayin** [comment] 2019-04-08 01:45
```
❯❯❯ gist list
1554687910.850 ERROR[gist] string indices must be integers
```

Has the gist API complete changed?

**Comment by jdowner** [comment] 2019-04-08 09:47
This is likely to be a change in you github account or on your computer. What message do you receive when you execute the command,
```
curl  https://api.github.com/gists?access_token=<your-personal-token>
```

**Comment by wookayin** [comment] 2019-04-08 19:31
Hi @jdowner, thanks for your quick response! It was actually my fault to have an invalid token that was misconfigured -- sorry about that. I was seeing

```
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```

After issuing a new token, now it works. However it would be great we can improve the error message -- I've changed the title of this issue.

**Comment by jdowner** [comment] 2019-04-08 19:50
I'm pleased to hear that you were able to quickly fix the issue. I agree, the error message is unhelpful and should be fixed.

**Comment by paluchas** [comment] 2019-04-30 11:08
Agree, the error message is somehow misleading. 

In addition there is some issue with the functionality too. I have tried to create a gist with this command
```
(gist-project) python-enviroemnts ❯ gist create lua-python-redis-example
# Edit file in Vim on quit save
1556622151.781 ERROR[gist] 'html_url'
```

However, if a existing file is used (no use of editor) than It works
```
(gist-project) python-enviroemnts ❯ gist create "Example shows how to run Lua script in Redis as called from Python" lua-python-redis-example.py
https://gist.github.com/5c93f3e90ea2e51a5c32d0152b4011c1
```
This behaviour is related to _python_gist-0.6.2-py3-none-any.whl_ version as installed via pip.

**Comment by veo-jdowner** [comment] 2019-04-30 12:07
@paluchas sorry to hear that -- I know that must be frustrating. I'm a bit confused about the difference in these examples. In the code, there is very little difference in what happens in these two cases. However, I was able to replicate the problem as a special case: if the file is empty, an error does occur. This is true in either case (from file or editor). Did you write the contents of the file before quiting the editor? Obviously this is a bug I have to fix, but I am trying to figure out if it is the cause of the problem you experienced.

**Comment by jdowner** [comment] 2019-04-30 12:11
@paluchas sorry to hear that -- I know that must be frustrating. I'm a bit confused about the difference in these examples. In the code, there is very little difference in what happens in these two cases. However, I was able to replicate the problem as a special case: if the file is empty, an error does occur. This is true in either case (from file or editor). Did you write the contents of the file before quiting the editor? Obviously this is a bug I have to fix, but I am trying to figure out if it is the cause of the problem you experienced.

**Closed** 2019-05-03 12:46 UTC
